# Generated by Django 4.1.2 on 2023-07-27 15:35

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_tempbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to=Account.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='tempbranch',
            name='branch',
            field=models.CharField(default='CS', max_length=10),
        ),
    ]
