# Generated by Django 4.1.2 on 2023-05-22 18:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postalcode', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2023, 5, 22))),
                ('name', models.CharField(default='name', max_length=30)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.CharField(max_length=50)),
                ('branch', models.CharField(default='CS', max_length=10)),
                ('adm_year', models.IntegerField(default=2020)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceR.org')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2023, 5, 22))),
                ('name', models.CharField(default='name', max_length=30)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.CharField(max_length=50)),
                ('branch', models.CharField(default='CS', max_length=10)),
                ('adm_year', models.IntegerField(default=2020)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceR.org')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2023, 5, 22))),
                ('name', models.CharField(default='name', max_length=30)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.CharField(max_length=50)),
                ('branch', models.CharField(default='CS', max_length=10)),
                ('adm_year', models.IntegerField(default=2020)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceR.org')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2023, 5, 22))),
                ('name', models.CharField(default='name', max_length=30)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.CharField(max_length=50)),
                ('branch', models.CharField(default='CS', max_length=10)),
                ('adm_year', models.IntegerField(default=2020)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceR.org')),
            ],
        ),
    ]
