# Generated by Django 4.1.2 on 2023-05-23 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancece',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
        migrations.AlterField(
            model_name='attendancecs',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
        migrations.AlterField(
            model_name='attendanceec',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
        migrations.AlterField(
            model_name='attendanceme',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
    ]
