# Generated by Django 4.1.2 on 2023-07-27 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceR', '0002_alter_attendancece_date_alter_attendancecs_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancece',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendancecs',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendanceec',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendanceme',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
